language: node_js
node_js:
    - "5"
before_script:
    - npm install -g gulp bower
sudo: required
services:
    - docker
script:
    - bower install
    - gulp --env=prod
    - '[ "${TRAVIS_PULL_REQUEST}" != "false" ] || gulp docker'
