angular.module("gerritDashboard",
    [
        "ui.router",
        "ui.bootstrap",
        "gerritDashboard.footer",
        "gerritDashboard.dashboard",
        "gerritDashboard.stats",
        "gerritDashboard.constants"
    ]);
