angular.module("gerritDashboard",
    [
        "ui.router",
        "ui.bootstrap",
        "gerritDashboard.footer",
        "gerritDashboard.dashboard",
        "gerritDashboard.stats",
        "gerritDashboard.header",
        "gerritDashboard.constants",
        "gerritDashboard.i18n"
    ]);
